/*module.exports =  `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlYsiV3DsG+t8OFMLyhdmG2P2J4GJwmwb1rKKcDZmTxEphPiYTeFIg4IFEiqDCATAPHs8UHypphZTK6LlzANyTzl9LjQS6BYVQk81LhQ29dxyrXgwkRw9RdWaMPtcXRD4h6ovx6FQjwQlBM5vaHaJOHhEorHOSyd/deTvcS+hRSQIDAQAB
-----END PUBLIC KEY-----
`
  */
module.exports =  `-----BEGIN PUBLIC KEY-----
YWJmZjI4NDU5ZTg5MGRmZGViZTljZGJjZWJiYTJhYWM2OGY3N2MxOGE2NmYxMWNmMDAxMWE4ZTVjY2UzMjM5Nw
-----END PUBLIC KEY-----
`
